apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: databases
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: postgresql-secrets
    creationPolicy: Owner

  data:
    - secretKey: postgres-password
      remoteRef:
        key: database/postgresql
        property: admin-password

    - secretKey: password
      remoteRef:
        key: database/postgresql
        property: user-password

# Note: Before deploying, ensure these secrets exist in your backend:
#
# For Vault:
#   vault kv put secret/database/postgresql \
#     admin-password="<ADMIN_PASSWORD>" \
#     user-password="<USER_PASSWORD>"
#
# For AWS Secrets Manager:
#   aws secretsmanager create-secret --name database/postgresql \
#     --secret-string '{"admin-password":"<ADMIN_PASSWORD>","user-password":"<USER_PASSWORD>"}'
#
# For GCP Secret Manager:
#   echo -n "<ADMIN_PASSWORD>" | gcloud secrets create database-postgresql-admin-password --data-file=-
#   echo -n "<USER_PASSWORD>" | gcloud secrets create database-postgresql-user-password --data-file=-
