apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    # CloudNativePG operator configuration
    crds:
      create: true

    # Monitoring configuration
    monitoring:
      podMonitorEnabled: false  # Set to true if Prometheus Operator is installed

    # Resource limits for operator
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
