apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/managed-by: Flux
spec:
  interval: 10m  # Reconcile every 10 minutes - adjust based on change frequency
  chart:
    spec:
      chart: apisix
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: apisix
      interval: 5m

  values:
    # Gateway configuration
    gateway:
      enabled: true
      type: NodePort

    # Ingress controller configuration
    ingress-controller:
      enabled: true
      config:
        apisix:
          serviceNamespace: apisix

    # etcd configuration (required dependency)
    etcd:
      enabled: true
      replicaCount: 3

  install:
    createNamespace: false  # Using explicit namespace.yaml for label control
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3
